create table roles (id integer generated by default as identity, name varchar(20), primary key (id));
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id));
create table users (id bigint generated by default as identity, password varchar(255), username varchar(255), primary key (id))