create table roles (
    id integer generated by default as identity,
    name varchar(20), primary key (id)
                   );

create table user_roles (
    user_id bigint not null,
    role_id integer not null,
    primary key (user_id, role_id)
                        );

create table users (
    id bigint generated by default as identity,
    password varchar(255),
    username varchar(255),
    primary key (id)
                   );
create table projects (
    id bigint not null generated by default as identity ,
    title varchar(50),
    parent_project_id bigint,
    root_project_id bigint,
    primary key (id));

create table tasks (
    id bigint generated by default as identity,
    task_date_of_create timestamp,
    task_date_of_status_change timestamp,
    task_editor varchar(255),
    task_info varchar(255),
    task_name varchar(255),
    task_owner varchar(255),
    task_status varchar(255),
    task_type varchar(255),
    project_id bigint,
    primary key (id))